#!/bin/bash

# Show all available helper scripts
echo "🚀 Apache Kafka 4.0.0 + Go (franz-go) + Java Development Helper Scripts"
echo "========================================================================="
echo ""
echo "Environment Management:"
echo "  ./scripts/start.sh           - Start Apache Kafka 4.0.0, Go, and Java containers"
echo "  ./scripts/stop.sh            - Stop containers"
echo "  ./scripts/test-connection.sh - Test Kafka connection"
echo ""
echo "Go Development:"
echo "  ./scripts/shell.sh           - Access Go development container"
echo "  ./scripts/producer.sh        - Run Go producer"
echo "  ./scripts/consumer.sh        - Run Go consumer"
echo ""
echo "Java Development:"
echo "  ./scripts/java-shell.sh      - Access Java development container"
echo "  ./scripts/java-build.sh      - Build Java project with Maven"
echo "  ./scripts/java-producer.sh   - Run Java producer"
echo "  ./scripts/java-consumer.sh   - Run Java consumer"
echo ""
echo "Kafka Management:"
echo "  ./scripts/kafka-topics.sh    - Manage Kafka topics"
echo "    Examples:"
echo "      ./scripts/kafka-topics.sh list"
echo "      ./scripts/kafka-topics.sh create my-topic"
echo "      ./scripts/kafka-topics.sh describe my-topic"
echo "      ./scripts/kafka-topics.sh delete my-topic"
echo ""
echo "Monitoring:"
echo "  ./scripts/logs.sh            - View container logs"
echo "  ./scripts/logs.sh kafka4     - View Kafka logs"
echo "  ./scripts/logs.sh dev-golang - View Go container logs"
echo "  ./scripts/logs.sh dev-java   - View Java container logs"
echo ""
echo "Direct Docker Commands:"
echo "  docker compose up -d         - Start containers"
echo "  docker compose down          - Stop containers"
echo "  docker compose down -v       - Stop and remove volumes"
echo "  docker compose ps            - Show container status"
echo "  docker compose exec dev-golang sh - Access Go container"
echo "  docker compose exec dev-java bash - Access Java container"
echo ""
echo "📝 Project Structure:"
echo "  /workspace         - Current directory mounted in containers"
echo "  /golang-project    - Go project (mounted from ./golang-project)"
echo "  /java-project      - Java project with Maven structure"
echo "    ├── pom.xml      - Maven project configuration"
echo "    ├── src/main/java/com/example/kafka/"
echo "    │   ├── KafkaProducer.java"
echo "    │   └── KafkaConsumer.java"
echo "    └── target/      - Compiled classes (auto-generated)"
echo ""
echo "🔗 Connection Info:"
echo "  Kafka from host:     localhost:9093"
echo "  Kafka from container: kafka4:29092"
echo "  JMX monitoring:      localhost:9997" 