# Lima VM configuration
arch: "aarch64"

# Use native macOS virtualization
vmType: "vz"

# VM resources
cpus: 4
memory: "16GiB"
disk: "128GiB"

# Use Ubuntu latest ARM64 image
images:
  - location: "https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-arm64.img"
    arch: "aarch64"

# Mount home directory and docker socket
mounts:
  - location: "~"
    writable: true
  - location: "/Users/johndavis/data"
    mountPoint: "/data"
    writable: true

# SSH configuration
ssh:
  forwardAgent: true
  loadDotSSHPubKeys: true
  localPort: 22222
  forwardX11: false
  forwardX11Trusted: false

# Docker support
provision:
  - mode: system
    script: |
      #!/bin/bash
      apt-get update
      apt-get install -y docker.io docker-compose
      addgroup lima docker
      systemctl enable docker
      systemctl start docker
      usermod -aG docker ubuntu
      
      # Create 32GB swap file
      fallocate -l 32G /swapfile
      chmod 600 /swapfile
      mkswap /swapfile
      swapon /swapfile
      
      # Make swap permanent
      echo '/swapfile none swap sw 0 0' >> /etc/fstab
      
      # Configure swappiness (optional - reduces swap usage)
      echo 'vm.swappiness=10' >> /etc/sysctl.conf 