version: '3.9'

x-config: &x-config
  ENVIRONMENT: 'dev'
  KAFKA_BOOTSTRAP_SERVERS: 'PLAINTEXT://redpanda:9092'
  REDIS_URI: 'redis://redis:6379'

services:
  redis:
    image: bitnami/redis:6.2
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    healthcheck:
      test: 'redis-cli ping'
      interval: '5s'
      timeout: '1s'
      retries: 20
    ports:
      - '6379'
  redpanda:
    image: vectorized/redpanda:v22.1.7
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://redpanda:9092
      - --pandaproxy-addr
      - PLAINTEXT://0.0.0.0:28082,OUTSIDE://0.0.0.0:8082
      - --advertise-pandaproxy-addr
      - PLAINTEXT://redpanda:28082,OUTSIDE://redpanda:8082
      - --set
      - "redpanda.auto_create_topics_enabled=true"
    ports:
      - '8082' # http pandaproxy rest api
      - '9092' # kafka wire protocol
    healthcheck:
      test: 'curl --fail --silent http://localhost:8082/topics || exit 1'
      interval: '5s'
      timeout: '1s'
      retries: 20
    volumes:
      - '/var/lib/redpanda/data'
  svc:
    build:
      context: omni
      dockerfile: Dockerfile
    #command: ["sleep", "infinity"]
    command: ["npx", "tsx", "/root/app/omni/src/server/main.ts"]
    healthcheck:
      test: exit 0
      interval: 10s
    volumes:
      - '.:/root/app' # will mount local source code into the container
    depends_on:
      redis:
        condition: service_healthy
      redpanda:
        condition: service_healthy
    environment:
      <<: *x-config
    ports:
      - '80'
  webchat:
    build:
      context: examples/web.chat
      dockerfile: Dockerfile
    #command: ["sleep", "infinity"]
    command: ["npm", "run", "all"]
    healthcheck:
      test: exit 0
      interval: 10s
    volumes:
      - './examples/web.chat:/root/app' # will mount local source code into the container
    depends_on:
      svc:
        condition: service_healthy
    environment:
      <<: *x-config
    ports:
      - '8080'
  caddy:
    image: caddy:latest
    volumes:
      - ./etc/caddy:/etc/caddy
    healthcheck:
      test: exit 0
      interval: 10s
    ports:
      - '80'
  cloudflare:
    image: cloudflare/cloudflared:latest
    command: ["tunnel", "--no-autoupdate", "--url", "http://caddy:80"]
networks:
  default: {}
